// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisTMiceByT1lhtU8txKNOWjk9lOj6H78',
    appId: '1:264033732909:web:339714b8b34de6387daba4',
    messagingSenderId: '264033732909',
    projectId: 'employee-onboarding-app-4b36b',
    authDomain: 'employee-onboarding-app-4b36b.firebaseapp.com',
    storageBucket: 'employee-onboarding-app-4b36b.firebasestorage.app',
    measurementId: 'G-TH71QVYNS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxTgzBEmecX7tejKq1Pk4ZQlkQ5mgXxE',
    appId: '1:264033732909:android:10c285bdb6dc52137daba4',
    messagingSenderId: '264033732909',
    projectId: 'employee-onboarding-app-4b36b',
    storageBucket: 'employee-onboarding-app-4b36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQQve9m1Mp66Yimd4AofHpwT7I_HyTtM',
    appId: '1:264033732909:ios:a47dd33d4de9a3647daba4',
    messagingSenderId: '264033732909',
    projectId: 'employee-onboarding-app-4b36b',
    storageBucket: 'employee-onboarding-app-4b36b.firebasestorage.app',
    iosBundleId: 'com.example.employeeOnboardingApp',
  );
}
